// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface SharedMap {
    Center:                       Center;
    Zoom:                         number;
    ActiveBaseLayer:              string;
    ClusteredMarkers:             boolean;
    Markers:                      Marker[];
    Ricerche:                     any[];
    WMSOverlays:                  WMSOverlay[];
    ComuniEvidenziati:            ComuniEvidenziati;
    TribunaleEvidenziato:         TribunaleEvidenziato;
    DrawnItems:                   DrawnItems;
    ElencoNazionaleActive:        boolean;
    ElencoNazionaleHeatmapActive: boolean;
}

export interface Center {
    lat: number;
    lng: number;
}

export interface ComuniEvidenziati {
    Active:   boolean;
    Opacity:  number;
    Comuni:   any[];
    Negativo: boolean;
}

export interface DrawnItems {
    type:     string;
    features: any[];
}

export interface Marker {
    Etichetta:           string;
    Trascinabile:        boolean;
    Coordinate:          Center;
    Heading:             number;
    Pitch:               number;
    Icona:               Icona;
    IdRicerca:           null;
    Denominazione:       Denominazione;
    Provenienza:         Provenienza;
    Prezzo:              number | null;
    Url:                 string;
    Superficie:          number | null;
    NumeroLocali:        string;
    Note:                string;
    Data:                string;
    IdAnnuncio:          null;
    ProvenienzaAnnuncio: string;
}

export enum Denominazione {
    Albergo = "Albergo",
    Appartamento = "Appartamento",
    AreaStradale = "Area stradale",
    AreaUrbana = "Area urbana",
    AutorimessaGarage = "Autorimessa - Garage",
    Box = "Box",
    CabinaElettrica = "Cabina elettrica",
    CapannoneAgricolo = "Capannone agricolo",
    CapannoneCommerciale = "Capannone commerciale",
    Cappella = "Cappella",
    Casa = "Casa",
    CasaColonica = "Casa colonica",
    CentraleIdroelettrica = "Centrale idroelettrica",
    ComplessoArtigianale = "Complesso artigianale",
    ComplessoCommerciale = "Complesso commerciale",
    ComplessoImmobiliare = "Complesso immobiliare",
    ComplessoSportivo = "Complesso sportivo",
    ComplessoTuristico = "Complesso turistico",
    DepositoAttrezziAgricoli = "Deposito attrezzi agricoli",
    DistributoreDiCarburante = "Distributore di carburante",
    FabbricatoCommerciale = "Fabbricato commerciale",
    FabbricatoDiruto = "Fabbricato diruto",
    FabbricatoIntero = "Fabbricato intero",
    FabbricatoResidenziale = "Fabbricato residenziale",
    FabbricatoRurale = "Fabbricato rurale",
    FondoRustico = "Fondo rustico",
    GruppoDiAppartamenti = "Gruppo di Appartamenti",
    ImmobileNONCLASSIFICATO = "_Immobile NON CLASSIFICATO",
    ImmobilePubblicoGenerico = "Immobile pubblico - Generico",
    ImpiantoFotovoltaico = "Impianto Fotovoltaico",
    LaboratorioArtigianale = "Laboratorio artigianale",
    LastricoSolareOTerrazza = "Lastrico solare o terrazza",
    Magazzino = "Magazzino",
    NegozioLocaleCommercialeFondo = "Negozio / locale commerciale / fondo",
    Opificio = "Opificio",
    Palazzina = "Palazzina",
    Palestra = "Palestra",
    PorzioneDiFabbricato = "Porzione di fabbricato",
    PostoAutoCoperto = "Posto auto coperto",
    PostoAutoScoperto = "Posto auto scoperto",
    ReliquatoStradale = "Reliquato stradale",
    Rustico = "Rustico",
    Stalla = "Stalla",
    Supermercato = "Supermercato",
    TerrenoAgricolo = "Terreno agricolo",
    TerrenoEdificabile = "Terreno edificabile",
    TerrenoEdificato = "Terreno edificato",
    UfficioPrivatoOStudioProfessionale = "Ufficio privato o studio professionale",
    Villino = "Villino",
}

export enum Icona {
    D10PNG = "d_10.png",
    D11PNG = "d_11.png",
    D12PNG = "d_12.png",
    D13PNG = "d_13.png",
    D1PNG = "d_1.png",
    D2PNG = "d_2.png",
    D3PNG = "d_3.png",
    D4PNG = "d_4.png",
    D5PNG = "d_5.png",
    D6PNG = "d_6.png",
    D7PNG = "d_7.png",
    D8PNG = "d_8.png",
    D9PNG = "d_9.png",
}

export enum Provenienza {
    Compravendita = "compravendita",
}

export interface TribunaleEvidenziato {
    Active:    boolean;
    Opacity:   number;
    Tribunale: null;
}

export interface WMSOverlay {
    NomeInterno: string;
    Active:      boolean;
    Opacity:     number;
}
